name: GitHub Metrics Terminal

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Terminal Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: scryst # Replace with your GitHub username
          filename: metrics.terminal.svg
          template: terminal
          base: header, activity, community, repositories, metadata, lines, stars, people, following, topics, gists, discussions, projects, achievements, notable, code, tweets # Added tweets
          plugins_languages: yes
          plugins_languages_limit: 20
          plugins_languages_details: bytes, percentage, lines
          plugins_languages_threshold: 0%
          plugins_lines: yes
          plugins_repositories: yes
          plugins_repositories_limit: 10
          plugins_repositories_forks: yes
          plugins_repositories_stargazers: yes
          plugins_repositories_affiliations: owner, collaborator, organization
          plugins_achievements: yes
          plugins_achievements_threshold: C
          plugins_achievements_secrets: yes
          plugins_discussions: yes
          plugins_discussions_categories: yes
          plugins_discussions_categories_limit: 10
          plugins_gists: yes
          plugins_gists_limit: 10
          plugins_habits: yes
          plugins_habits_from: 365 # Increased to 365 days
          plugins_habits_facts: yes
          plugins_introduction: yes
          plugins_introduction_title: "My GitHub Statistics"
          plugins_topics: yes
          plugins_topics_limit: 15
          plugins_topics_mode: mastered
          plugins_tweets: yes #Enables tweets plugin. Requires external configuration
          config_timezone: America/Los_Angeles # Replace with your timezone
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "Update metrics.terminal.svg - [Skip GitHub Action]"
          output_action: commit
          output_condition: always
          optimize: css, xml
          config_display: columns
          config_twemoji: yes
          config_gemoji: yes
          config_octicon: no
          config_animations: yes
          config_base64: yes
          config_padding: 0, 8 + 11%
          config_output: svg
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          notice_releases: yes
          use_prebuilt_image: yes
          plugins_errors_fatal: no
          debug: false
          verify: false
          debug_flags: ""
          debug_print: no
          dryrun: false
          experimental_features: ""
          use_mocked_data: false
