name: GitHub Metrics Terminal

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Terminal Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: scryst # Replace with your GitHub username
          filename: metrics.terminal.svg
          template: terminal
          base: header, activity, metadata, stars, projects, code, community, people, following #Removed repositories
          plugin_languages: yes
          plugin_languages_limit: 20
          plugin_languages_details: bytes, percentage, lines
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used
          plugin_languages_recent_categories: markup, programming, data, scripting, prose, unknown
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_from: 365
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 10
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: "My GitHub Stats"
          config_timezone: America/Los_Angeles # Replace with your timezone
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "Update metrics.terminal.svg - [Skip GitHub Action]"
          output_action: commit
          output_condition: always
          optimize: css, xml
          config_display: columns
          config_twemoji: yes
          config_gemoji: yes
          config_octicon: no
          config_animations: yes
          config_base64: yes
          config_padding: 0, 8 + 11%, 50, 8 + 11%
          config_output: svg
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          notice_releases: yes
          use_prebuilt_image: yes
          plugins_errors_fatal: no
          debug: false
          verify: false
          debug_flags: ""
          debug_print: no
          dryrun: false
          experimental_features: ""
          use_mocked_data: false
